In [1]:
'''>>>>> start CodeP2.4
    V.P. Carey ME249, Spring 2021

Intro to Neural Network Modeling 
Keras model for hybrid solar/fossil-fuel gas turbine power system'''

#import useful packages
import keras
import pandas as pd
from keras.models import Sequential
import numpy as np
import keras.backend as kb
import tensorflow as tf
#the follwoing 2 lines are only needed for Mac OS machines
# import os
# os.environ['KMP_DUPLICATE_LIB_OK']='True'

#create input data array
# meadian values of input variables
Tmed = 293.
gamed = 0.25
qsmed = 1250.
#T1(K), gamma, , qsol(kW):

xdata =  [[ 318.0 , 0.0 , 500.0 ], [ 318.0 , 0.0 , 1000.0 ]]
xdata.append([ 318.0 , 0.0 , 1500.0 ])
xdata.append([ 318.0 , 0.0 , 2000.0 ])
xdata.append([ 318.0 , 0.0 , 2500.0 ])
xdata.append([ 318.0 , 0.25 , 500.0 ])
xdata.append([ 318.0 , 0.25 , 1000.0 ])
xdata.append([ 318.0 , 0.25 , 1500.0 ])
xdata.append([ 318.0 , 0.25 , 2000.0 ])
xdata.append([ 318.0 , 0.25 , 2500.0 ])
xdata.append([ 318.0 , 0.5 , 500.0 ])
xdata.append([ 318.0 , 0.5 , 1000.0 ])
xdata.append([ 318.0 , 0.5 , 1500.0 ])
xdata.append([ 318.0 , 0.5 , 2000.0 ])
xdata.append([ 318.0 , 0.5 , 2500.0 ])
  
xdata.append([ 303.0 , 0.0 , 500.0 ])
xdata.append([ 303.0 , 0.0 , 1000.0 ])
xdata.append([ 303.0 , 0.0 , 1500.0 ])
xdata.append([ 303.0 , 0.0 , 2000.0 ])
xdata.append([ 303.0 , 0.0 , 2500.0 ])
xdata.append([ 303.0 , 0.25 , 500.0 ])
xdata.append([ 303.0 , 0.25 , 1000.0 ])
xdata.append([ 303.0 , 0.25 , 1500.0 ])
xdata.append([ 303.0 , 0.25 , 2000.0 ])
xdata.append([ 303.0 , 0.25 , 2500.0 ])
xdata.append([ 303.0 , 0.5 , 500.0 ])
xdata.append([ 303.0 , 0.5 , 1000.0 ])
xdata.append([ 303.0 , 0.5 , 1500.0 ])
xdata.append([ 303.0 , 0.5 , 2000.0 ])
xdata.append([ 303.0 , 0.5 , 2500.0 ])
  
xdata.append([ 288.0 , 0.0 , 500.0 ])
xdata.append([ 288.0 , 0.0 , 1000.0 ])
xdata.append([ 288.0 , 0.0 , 1500.0 ])
xdata.append([ 288.0 , 0.0 , 2000.0 ])
xdata.append([ 288.0 , 0.0 , 2500.0 ])
xdata.append([ 288.0 , 0.25 , 500.0 ])
xdata.append([ 288.0 , 0.25 , 1000.0 ])
xdata.append([ 288.0 , 0.25 , 1500.0 ])
xdata.append([ 288.0 , 0.25 , 2000.0 ])
xdata.append([ 288.0 , 0.25 , 2500.0 ])
xdata.append([ 288.0 , 0.5 , 500.0 ])
xdata.append([ 288.0 , 0.5 , 1000.0 ])
xdata.append([ 288.0 , 0.5 , 1500.0 ])
xdata.append([ 288.0 , 0.5 , 2000.0 ])
xdata.append([ 288.0 , 0.5 , 2500.0 ])
  
xdata.append([ 268.0 , 0.0 , 500.0 ])
xdata.append([ 268.0 , 0.0 , 1000.0 ])
xdata.append([ 268.0 , 0.0 , 1500.0 ])
xdata.append([ 268.0 , 0.0 , 2000.0 ])
xdata.append([ 268.0 , 0.0 , 2500.0 ])
xdata.append([ 268.0 , 0.25 , 500.0 ])
xdata.append([ 268.0 , 0.25 , 1000.0 ])
xdata.append([ 268.0 , 0.25 , 1500.0 ])
xdata.append([ 268.0 , 0.25 , 2000.0 ])
xdata.append([ 268.0 , 0.25 , 2500.0 ])
xdata.append([ 268.0 , 0.5 , 500.0 ])
xdata.append([ 268.0 , 0.5 , 1000.0 ])
xdata.append([ 268.0 , 0.5 , 1500.0 ])
xdata.append([ 268.0 , 0.5 , 2000.0 ])
xdata.append([ 268.0 , 0.5 , 2500.0 ])



xarray= np.array(xdata)
# print (xdata)
# print (xarray)
# meadian values of output variables
almed = 60.
efmed = 0.4
# alpha, effsys

ydata =  [[ 35.1316 , 0.3808 ],[ 40.3764 , 0.38686 ]]
ydata.append([ 47.4620 , 0.3930 ])
ydata.append([ 57.5639 , 0.39949 ])
ydata.append([ 73.1286 , 0.40612 ])
ydata.append([ 49.1110 , 0.4023 ])
ydata.append([ 56.4428 , 0.40605 ])
ydata.append([ 66.3479 , 0.4098 ])
ydata.append([ 80.4695 , 0.413 ])
ydata.append([ 102.2276 , 0.4175 ])
ydata.append([ 63.0904 , 0.41540 ])
ydata.append([ 72.5092 , 0.4175 ])
ydata.append([ 85.2338, 0.4197 ])
ydata.append([ 103.3750 , 0.42192 ])
ydata.append([ 131.3266 , 0.4242 ])
  
ydata.append([ 34.273 , 0.3952 ])
ydata.append([ 38.99026 , 0.4012 ])
ydata.append([ 45.2133, 0.4073 ])
ydata.append([ 53.8000 , 0.4136 ])
ydata.append([ 66.4130 , 0.4201 ])
ydata.append([ 47.922 , 0.4178 ])
ydata.append([ 54.518 , 0.4215 ])
ydata.append([ 63.220 , 0.4252 ])
ydata.append([ 75.226 , 0.4290 ])
ydata.append([ 92.862 , 0.4329 ])
ydata.append([ 61.572 , 0.4315 ])
ydata.append([ 70.0468 , 0.43373 ])
ydata.append([ 81.226 , 0.43597 ])
ydata.append([ 96.653 , 0.4382 ])
ydata.append([ 119.3124 , 0.44045 ])
  
ydata.append([ 33.4521 , 0.40913 ])
ydata.append([ 37.6911, 0.4150 ])
ydata.append([ 43.1602 , 0.4209 ])
ydata.append([ 50.4858 , 0.4271 ])
ydata.append([ 60.8067 , 0.4334 ])
ydata.append([ 46.7865 , 0.4328 ])
ydata.append([ 52.7151 , 0.43646 ])
ydata.append([ 60.36425 , 0.44016 ])
ydata.append([ 70.6099 , 0.443926 ])
ydata.append([ 85.0447 , 0.4477 ])
ydata.append([ 60.1208 , 0.44721 ])
ydata.append([ 67.7391 , 0.44940 ])
ydata.append([ 77.56830 , 0.4516 ])
ydata.append([ 90.73410 , 0.4538 ])
ydata.append([ 109.2828 , 0.4560 ])
  
ydata.append([ 32.4123 , 0.42694 ])
ydata.append([ 36.0807 , 0.4325 ])
ydata.append([ 40.6854 , 0.4383 ])
ydata.append([ 46.6374 , 0.4442 ])
ydata.append([ 54.6293 , 0.4503 ])
ydata.append([ 45.3472 , 0.4519 ])
ydata.append([ 50.4796 , 0.4555 ])
ydata.append([ 56.9219 , 0.4591 ])
ydata.append([ 65.2492 , 0.4628 ])
ydata.append([ 76.4304 , 0.4665 ])
ydata.append([ 58.2822 , 0.4672 ])
ydata.append([ 64.8785 , 0.4693 ])
ydata.append([ 73.1584 , 0.4715 ])
ydata.append([ 83.8610 , 0.4738 ])
ydata.append([ 98.2316 , 0.4760 ])

yarray= np.array(ydata)
# print (ydata)
# print (yarray)

Using TensorFlow backend.


In [2]:
# Determine the median
xmedian = np.array([np.median(xarray[:,i]) for i in range(0,3)])
ymedian = np.array([np.median(yarray[:,i]) for i in range(0,2)])

In [3]:
for i in range(0,3):
    xarray[:,i] = xarray[:,i]/xmedian[i]

for i in range(0,2):
    yarray[:,i] = yarray[:,i]/ymedian[i]

In [4]:
print(xarray)
print(yarray)

[[1.07614213 0.         0.33333333]
 [1.07614213 0.         0.66666667]
 [1.07614213 0.         1.        ]
 [1.07614213 0.         1.33333333]
 [1.07614213 0.         1.66666667]
 [1.07614213 1.         0.33333333]
 [1.07614213 1.         0.66666667]
 [1.07614213 1.         1.        ]
 [1.07614213 1.         1.33333333]
 [1.07614213 1.         1.66666667]
 [1.07614213 2.         0.33333333]
 [1.07614213 2.         0.66666667]
 [1.07614213 2.         1.        ]
 [1.07614213 2.         1.33333333]
 [1.07614213 2.         1.66666667]
 [1.02538071 0.         0.33333333]
 [1.02538071 0.         0.66666667]
 [1.02538071 0.         1.        ]
 [1.02538071 0.         1.33333333]
 [1.02538071 0.         1.66666667]
 [1.02538071 1.         0.33333333]
 [1.02538071 1.         0.66666667]
 [1.02538071 1.         1.        ]
 [1.02538071 1.         1.33333333]
 [1.02538071 1.         1.66666667]
 [1.02538071 2.         0.33333333]
 [1.02538071 2.         0.66666667]
 [1.02538071 2.         1.  

In [15]:
# define neural network model

#As seen below, we have created four dense layers. 
#A dense layer is a layer in neural network that’s fully connected. 
#In other words, all the neurons in one layer are connected to all other neurons in the next layer.
#In the first layer, we need to provide the input shape, which is 1 in our case. 
#The activation function we have chosen is elu, which stands for exponential linear unit. .

from keras import backend as K
#initialize weights with values between -0.2 and 1.2
initializer = tf.keras.initializers.RandomUniform(minval= -0.2, maxval=1.2)

model = keras.Sequential([
    keras.layers.Dense(16, activation=K.elu, input_shape=[3]),
    keras.layers.Dense(32, activation=K.elu),
    keras.layers.Dense(16, activation=K.elu),
    keras.layers.Dense(2)
  ])


In [16]:
#We’re using RMSprop as our optimizer here. RMSprop stands for Root Mean Square Propagation. 
#It’s one of the most popular gradient descent optimization algorithms for deep learning networks. 
#RMSprop is an optimizer that’s reliable and fast.
#We’re compiling the mode using the model.compile function. The loss function used here 
#is mean squared error. After the compilation of the model, we’ll use the fit method with ~500 epochs.
#Number of epochs can be varied.

#from tf.keras import optimizers

sgd = keras.optimizers.RMSprop(0.015)
model.compile(loss='mean_absolute_error',optimizer=sgd)


In [17]:
#After the compilation of the model, we’ll use the fit method with 500 epochs.
#I started with epochs value of 100 and then tested the model after training. 
#The prediction was not that good. Then I modified the number of epochs to 200 and tested the model again. 
#Accuracy had improved slightly, but figured I’d give it one more try. Finally, at 500 epochs 
#I found acceptable prediction accuracy.

#The fit method takes three parameters; namely, x, y, and number of epochs. 
#During model training, if all the batches of data are seen by the model once, 
#we say that one epoch has been completed.

# Add an early stopping callback
es = keras.callbacks.EarlyStopping(
    monitor='loss', 
    mode='min', 
    patience = 20, 
    restore_best_weights = True, 
    verbose=1)
# Add a checkpoint where loss is minimum, and save that model
mc = keras.callbacks.ModelCheckpoint('best_model.SB', monitor='loss', 
                     mode='min',  verbose=1, save_best_only=True)

historyData = model.fit(xarray,yarray,epochs=600,callbacks=[es])

loss_hist = historyData.history['loss']
#The above line will return a dictionary, access it's info like this:
best_epoch = np.argmin(historyData.history['loss']) + 1
print ('best epoch = ', best_epoch)
print('smallest loss =', np.min(loss_hist))


Epoch 1/600
60/60 [==============================] - 1s 18ms/step - loss: 1.4012
Epoch 2/600
60/60 [==============================] - 0s 234us/step - loss: 0.5958
Epoch 3/600
60/60 [==============================] - 0s 550us/step - loss: 0.3274
Epoch 4/600
60/60 [==============================] - 0s 605us/step - loss: 0.2925
Epoch 5/600
60/60 [==============================] - 0s 929us/step - loss: 0.2220
Epoch 6/600
60/60 [==============================] - 0s 555us/step - loss: 0.2298
Epoch 7/600
60/60 [==============================] - 0s 1ms/step - loss: 0.4086
Epoch 8/600
60/60 [==============================] - 0s 418us/step - loss: 0.1226
Epoch 9/600
60/60 [==============================] - 0s 373us/step - loss: 0.2353
Epoch 10/600
60/60 [==============================] - 0s 172us/step - loss: 0.2196
Epoch 11/600
60/60 [==============================] - 0s 318us/step - loss: 0.2012
Epoch 12/600
60/60 [==============================] - 0s 145us/step - loss: 0.1949
Epoch 13/600
60/

In [18]:
sgd = tf.keras.optimizers.RMSprop(0.005)
model.compile(loss='mean_absolute_error',optimizer=sgd)

historyData = model.fit(xarray,yarray,epochs=600,callbacks=[es])

Epoch 1/600
60/60 [==============================] - 1s 16ms/step - loss: 0.2660
Epoch 2/600
60/60 [==============================] - 0s 222us/step - loss: 0.1509
Epoch 3/600
60/60 [==============================] - 0s 419us/step - loss: 0.1199
Epoch 4/600
60/60 [==============================] - 0s 594us/step - loss: 0.0979
Epoch 5/600
60/60 [==============================] - 0s 443us/step - loss: 0.1126
Epoch 6/600
60/60 [==============================] - 0s 160us/step - loss: 0.0959
Epoch 7/600
60/60 [==============================] - 0s 134us/step - loss: 0.1282
Epoch 8/600
60/60 [==============================] - 0s 185us/step - loss: 0.1125
Epoch 9/600
60/60 [==============================] - 0s 355us/step - loss: 0.0903
Epoch 10/600
60/60 [==============================] - 0s 399us/step - loss: 0.0964
Epoch 11/600
60/60 [==============================] - 0s 578us/step - loss: 0.0911
Epoch 12/600
60/60 [==============================] - 0s 308us/step - loss: 0.0915
Epoch 13/600
6

In [19]:
sgd = tf.keras.optimizers.RMSprop(0.001)
model.compile(loss='mean_absolute_error',optimizer=sgd)

historyData = model.fit(xarray,yarray,epochs=600,callbacks=[es])

Epoch 1/600
60/60 [==============================] - 1s 15ms/step - loss: 0.0758
Epoch 2/600
60/60 [==============================] - 0s 218us/step - loss: 0.0639
Epoch 3/600
60/60 [==============================] - 0s 246us/step - loss: 0.0678
Epoch 4/600
60/60 [==============================] - 0s 551us/step - loss: 0.0625
Epoch 5/600
60/60 [==============================] - 0s 312us/step - loss: 0.0665
Epoch 6/600
60/60 [==============================] - 0s 502us/step - loss: 0.0628
Epoch 7/600
60/60 [==============================] - 0s 320us/step - loss: 0.0684
Epoch 8/600
60/60 [==============================] - 0s 340us/step - loss: 0.0629
Epoch 9/600
60/60 [==============================] - 0s 557us/step - loss: 0.0630
Epoch 10/600
60/60 [==============================] - 0s 495us/step - loss: 0.0629
Epoch 11/600
60/60 [==============================] - 0s 317us/step - loss: 0.0656
Epoch 12/600
60/60 [==============================] - 0s 562us/step - loss: 0.0625
Epoch 13/600
6

60/60 [==============================] - 0s 393us/step - loss: 0.0494
Epoch 100/600
60/60 [==============================] - 0s 257us/step - loss: 0.0490
Epoch 101/600
60/60 [==============================] - 0s 184us/step - loss: 0.0500
Epoch 102/600
60/60 [==============================] - 0s 268us/step - loss: 0.0486
Epoch 103/600
60/60 [==============================] - 0s 139us/step - loss: 0.0522
Epoch 104/600
60/60 [==============================] - 0s 180us/step - loss: 0.0532
Epoch 105/600
60/60 [==============================] - 0s 320us/step - loss: 0.0506
Epoch 106/600
60/60 [==============================] - 0s 297us/step - loss: 0.0514
Epoch 107/600
60/60 [==============================] - 0s 166us/step - loss: 0.0499
Epoch 108/600
60/60 [==============================] - 0s 267us/step - loss: 0.0461
Epoch 109/600
60/60 [==============================] - 0s 275us/step - loss: 0.0469
Epoch 110/600
60/60 [==============================] - 0s 238us/step - loss: 0.0472
Epoch 

In [20]:
sgd = tf.keras.optimizers.RMSprop(0.0005)
model.compile(loss='mean_absolute_error',optimizer=sgd)

historyData = model.fit(xarray,yarray,epochs=600,callbacks=[es])

Epoch 1/600
60/60 [==============================] - 1s 14ms/step - loss: 0.0538
Epoch 2/600
60/60 [==============================] - 0s 194us/step - loss: 0.0415
Epoch 3/600
60/60 [==============================] - 0s 210us/step - loss: 0.0457
Epoch 4/600
60/60 [==============================] - 0s 320us/step - loss: 0.0406
Epoch 5/600
60/60 [==============================] - 0s 767us/step - loss: 0.0429
Epoch 6/600
60/60 [==============================] - 0s 581us/step - loss: 0.0415
Epoch 7/600
60/60 [==============================] - 0s 488us/step - loss: 0.0392
Epoch 8/600
60/60 [==============================] - ETA: 0s - loss: 0.042 - 0s 210us/step - loss: 0.0394
Epoch 9/600
60/60 [==============================] - 0s 219us/step - loss: 0.0426
Epoch 10/600
60/60 [==============================] - 0s 281us/step - loss: 0.0417
Epoch 11/600
60/60 [==============================] - 0s 258us/step - loss: 0.0393
Epoch 12/600
60/60 [==============================] - 0s 527us/step - los

Epoch 99/600
60/60 [==============================] - 0s 313us/step - loss: 0.0361
Epoch 100/600
60/60 [==============================] - 0s 223us/step - loss: 0.0318
Epoch 101/600
60/60 [==============================] - 0s 328us/step - loss: 0.0303
Epoch 102/600
60/60 [==============================] - 0s 141us/step - loss: 0.0310
Epoch 103/600
60/60 [==============================] - 0s 212us/step - loss: 0.0337
Epoch 104/600
60/60 [==============================] - 0s 153us/step - loss: 0.0390
Epoch 105/600
60/60 [==============================] - 0s 160us/step - loss: 0.0368
Epoch 106/600
60/60 [==============================] - 0s 162us/step - loss: 0.0362
Epoch 107/600
60/60 [==============================] - 0s 133us/step - loss: 0.0347
Epoch 108/600
60/60 [==============================] - 0s 236us/step - loss: 0.0323
Epoch 109/600
60/60 [==============================] - 0s 133us/step - loss: 0.0330
Epoch 110/600
60/60 [==============================] - 0s 132us/step - loss: 

In [21]:
sgd = tf.keras.optimizers.RMSprop(0.0001)
model.compile(loss='mean_absolute_error',optimizer=sgd)

historyData = model.fit(xarray,yarray,epochs=600,callbacks=[es])

Epoch 1/600
60/60 [==============================] - 1s 16ms/step - loss: 0.0318
Epoch 2/600
60/60 [==============================] - 0s 454us/step - loss: 0.0310
Epoch 3/600
60/60 [==============================] - 0s 836us/step - loss: 0.0301
Epoch 4/600
60/60 [==============================] - 0s 473us/step - loss: 0.0300
Epoch 5/600
60/60 [==============================] - 0s 382us/step - loss: 0.0302
Epoch 6/600
60/60 [==============================] - 0s 139us/step - loss: 0.0304
Epoch 7/600
60/60 [==============================] - 0s 153us/step - loss: 0.0300
Epoch 8/600
60/60 [==============================] - 0s 276us/step - loss: 0.0304
Epoch 9/600
60/60 [==============================] - 0s 387us/step - loss: 0.0301
Epoch 10/600
60/60 [==============================] - 0s 184us/step - loss: 0.0302
Epoch 11/600
60/60 [==============================] - 0s 128us/step - loss: 0.0308
Epoch 12/600
60/60 [==============================] - 0s 162us/step - loss: 0.0298
Epoch 13/600
6

60/60 [==============================] - 0s 355us/step - loss: 0.0285
Epoch 100/600
60/60 [==============================] - 0s 241us/step - loss: 0.0282
Epoch 101/600
60/60 [==============================] - 0s 217us/step - loss: 0.0277
Epoch 102/600
60/60 [==============================] - 0s 143us/step - loss: 0.0279
Epoch 103/600
60/60 [==============================] - 0s 162us/step - loss: 0.0279
Epoch 104/600
60/60 [==============================] - 0s 228us/step - loss: 0.0280
Epoch 105/600
60/60 [==============================] - 0s 140us/step - loss: 0.0280
Epoch 106/600
60/60 [==============================] - 0s 521us/step - loss: 0.0281
Epoch 107/600
60/60 [==============================] - 0s 213us/step - loss: 0.0278
Epoch 108/600
60/60 [==============================] - 0s 152us/step - loss: 0.0280
Epoch 109/600
60/60 [==============================] - 0s 190us/step - loss: 0.0275
Epoch 110/600
60/60 [==============================] - 0s 238us/step - loss: 0.0278
Epoch 

In [22]:
sgd = tf.keras.optimizers.RMSprop(0.0001)
model.compile(loss='mean_absolute_error',optimizer=sgd)

historyData = model.fit(xarray,yarray,epochs=600,callbacks=[es])

Epoch 1/600
60/60 [==============================] - 1s 16ms/step - loss: 0.0287
Epoch 2/600
60/60 [==============================] - 0s 227us/step - loss: 0.0287
Epoch 3/600
60/60 [==============================] - 0s 613us/step - loss: 0.0275
Epoch 4/600
60/60 [==============================] - 0s 381us/step - loss: 0.0272
Epoch 5/600
60/60 [==============================] - 0s 352us/step - loss: 0.0273
Epoch 6/600
60/60 [==============================] - 0s 589us/step - loss: 0.0272
Epoch 7/600
60/60 [==============================] - 0s 520us/step - loss: 0.0277
Epoch 8/600
60/60 [==============================] - 0s 548us/step - loss: 0.0274
Epoch 9/600
60/60 [==============================] - 0s 654us/step - loss: 0.0283
Epoch 10/600
60/60 [==============================] - 0s 373us/step - loss: 0.0271
Epoch 11/600
60/60 [==============================] - 0s 334us/step - loss: 0.0272
Epoch 12/600
60/60 [==============================] - 0s 424us/step - loss: 0.0273
Epoch 13/600
6

60/60 [==============================] - 0s 362us/step - loss: 0.0258
Epoch 100/600
60/60 [==============================] - 0s 312us/step - loss: 0.0262
Epoch 101/600
60/60 [==============================] - 0s 373us/step - loss: 0.0259
Epoch 102/600
60/60 [==============================] - 0s 153us/step - loss: 0.0264
Epoch 103/600
60/60 [==============================] - 0s 325us/step - loss: 0.0263
Epoch 104/600
60/60 [==============================] - 0s 203us/step - loss: 0.0258
Epoch 105/600
60/60 [==============================] - 0s 207us/step - loss: 0.0257
Epoch 106/600
60/60 [==============================] - 0s 386us/step - loss: 0.0274
Epoch 107/600
60/60 [==============================] - 0s 326us/step - loss: 0.0259
Epoch 108/600
60/60 [==============================] - 0s 342us/step - loss: 0.0259
Epoch 109/600
60/60 [==============================] - 0s 391us/step - loss: 0.0257
Epoch 110/600
60/60 [==============================] - 0s 394us/step - loss: 0.0257
Epoch 

60/60 [==============================] - 0s 140us/step - loss: 0.0255
Epoch 197/600
60/60 [==============================] - 0s 283us/step - loss: 0.0256
Epoch 198/600
60/60 [==============================] - 0s 144us/step - loss: 0.0260
Epoch 199/600
60/60 [==============================] - 0s 170us/step - loss: 0.0255
Epoch 200/600
60/60 [==============================] - 0s 146us/step - loss: 0.0252
Epoch 201/600
60/60 [==============================] - 0s 166us/step - loss: 0.0251
Epoch 202/600
60/60 [==============================] - 0s 471us/step - loss: 0.0257
Epoch 203/600
60/60 [==============================] - 0s 165us/step - loss: 0.0257
Epoch 204/600
60/60 [==============================] - 0s 147us/step - loss: 0.0260
Epoch 205/600
60/60 [==============================] - 0s 243us/step - loss: 0.0250
Epoch 206/600
60/60 [==============================] - ETA: 0s - loss: 0.022 - 0s 205us/step - loss: 0.0252
Epoch 207/600
60/60 [==============================] - 0s 544us/st

In [23]:
test = []
outpt=[]

#first point (row [0])comparison of data and prediction
# put in a loop to print comparion for all data points

test = [[ xarray[0][0] , xarray[0][1] , xarray[0][2] ]]
testarray = np.array(test)
outpt = model.predict(testarray)
print ('row [0] data:  T1= ', xarray[0][0]*Tmed, ', gam= ', xarray[0][1]*gamed, \
    ', qsol= ', xarray[0][2]*qsmed,', alpha= ', yarray[0][0]*almed,\
    ',  predicted alpha = ', outpt[0][0]*almed)

#20th point (row [20])comparison of data and prediction
test = [[ xarray[20][0] , xarray[20][1] , xarray[20][2] ]]
testarray = np.array(test)
outpt = model.predict(testarray)
print ('row [20] data:  T1= ', xarray[20][0]*Tmed, ', gam= ', xarray[0][1]*gamed, \
    ', qsol= ', xarray[20][2]*qsmed,', alpha= ', yarray[20][0]*almed,\
    ',  predicted alpha = ', outpt[0][0]*almed)

row [0] data:  T1=  315.3096446700507 , gam=  0.0 , qsol=  416.66666666666663 , alpha=  34.448739854239335 ,  predicted alpha =  37.17378258705139
row [20] data:  T1=  300.43654822335026 , gam=  0.0 , qsol=  416.66666666666663 , alpha=  46.990530214816786 ,  predicted alpha =  46.5719211101532
